### ISSUE TITLE
'ConsumedCapacity' object is not iterable

### ISSUE THREAD

**Issue by GarrettHeel** [stevearc/dynamo3#3]
After the ConsumedCapacity fixes in #2, I'm seeing the following exception being thrown from https://github.com/stevearc/dynamo3/blob/master/dynamo3/batch.py#L280

```'ConsumedCapacity' object is not iterable```

I'm guessing it's a result of something tripping https://github.com/stevearc/dynamo3/blob/master/dynamo3/connection.py#L246 before the batch operation on the same connection.

**Comment by stevearc** [comment]
Arg, I'll look into it. Sorry for the jankiness surrounding ConsumedCapacity; DynamoDB Local doesn't support it at all, so the tests have to be done entirely with mocks.

That said, I don't see any obvious places where another call to the connection could happen in between making the request and grabbing the `last_consumed_capacity`. Are you using the same connection in multiple threads? Is it a deterministic exception or does it just happen every so often?

Either way, making the connection stateful probably wasn't the right approach. I'll try stuffing it into the response object.

**Comment by stevearc** [comment]
If you have a chance, could you give this branch a try? https://github.com/stevearc/dynamo3/tree/capacity-test

**Comment by GarrettHeel** [comment]
We have a pretty standard setup with gevent but the connection is not shared between threads. The exception wasn't deterministic, it was only "ever so often" (but enough to be noticeable).

Will try out your branch soon and let you know how it goes! No sweat about the jankiness, happy to help figure it out.

**Comment by GarrettHeel** [comment]
A quick test of your branch looks positive - I was able to fetch consumed capacity for the Batch* operations and didn't see any exceptions. :+1:

**Comment by stevearc** [comment]
Great! I'll merge it in and cut a new release. Thanks for your help!

**Comment by stevearc** [comment]
Released `0.4.4`
