### ISSUE TITLE
Python 2 'str' incorrectly treated as STRING type during get

### ISSUE THREAD

**Issue by danfairs** [stevearc/dynamo3#6]
While testing with Flywheel and moto on Python 2.7, I found what seems to be an incompatibility. I think the problem is in `dynamo3`, but it's difficult to see a fix without potentially breaking existing data (I think!). Note that I haven't yet tested this on real DynamoDB - just using `moto`. However, the `dynamo3` code looks incorrect to me at first glance.

The issue seems to be that while Flywheel correctly interprets a `str` value as binary during the save (generating a 'B' Dynamo value), the `get` path involves `dynamo3`'s value encoding path, which seems to incorrectly encode `str` as a `STRING`, not a `BINARY`. 

Here's a repro script:

```
from flywheel import Engine, Model, Field
from moto import mock_dynamodb2


class Thing(Model):
    id = Field(type=str, hash_key=True)


@mock_dynamodb2
def go():
    engine = Engine()
    engine.connect('dummy-region')
    engine.register(Thing)
    engine.create_schema()

    thing_id='hello'
    thing = Thing(id=thing_id)
    engine.save([thing])

    loaded = engine.get(Thing, [thing.id])
    assert len(loaded) > 0

if __name__ == '__main__':
    go()
```

Here are the requirements I have in my Python venv:

```
botocore==1.4.93
docutils==0.13.1
-e git+git@github.com:danfairs/dynamo3.git@012f2d95649b8c942e0df930351809235200d6d6#egg=dynamo3
flywheel==0.5.1
httpretty==0.8.10
Jinja2==2.9.4
jmespath==0.9.0
MarkupSafe==0.23
moto==0.4.30
python-dateutil==2.6.0
pytz==2016.10
requests==2.12.4
six==1.10.0
Werkzeug==0.11.15
xmltodict==0.10.2
```

(The fork of dynamo3 has no changes from your master, at the time of writing)

What appears to be the offending lines of code are here:

https://github.com/stevearc/dynamo3/blob/012f2d95649b8c942e0df930351809235200d6d6/dynamo3/types.py#L114-L116

This doesn't make sense to me: if the user were genuinely storing binary data in a value, it doesn't make sense to do UTF8 decoding on it (what if it were an image, for example?).

**Comment by danfairs** [comment]
I've been able to work around this as follows:

```
import six
from dynamo3 import Dynamizer
from dynamo3.constants import BINARY

class MyDynamizer(Dynamizer):
    def __init__(self):
        super(MyDynamizer, self).__init__()
        self.register_encoder(
            six.binary_type, lambda _, v: (BINARY, v))

engine = Engine(namespace='test')
engine.connect('dummy-region')
engine.dynamo.dynamizer = MyDynamizer()
```

After that, I can successfully load instances I've previously saved with `moto`.

**Comment by stevearc** [comment]
The way that it was designed, if you want to store a binary blob in Dynamo, you would use [the Binary class](https://github.com/stevearc/dynamo3/blob/012f2d95649b8c942e0df930351809235200d6d6/dynamo3/types.py#L49) to wrap the blob before you send it to dynamo3 (e.g. `Binary(myblob)`). This is a pattern that I copied from boto when I was writing dynamo3, and I believe that it is because if you're writing code in python 2 you'll frequently end up with binary `str` types everywhere that you actually want to be treated as strings.

If you're using Flywheel, there is [a specific BinaryType](https://github.com/stevearc/flywheel/blob/570705333ac4c2d8193cdf96668303266b337c24/flywheel/fields/types.py#L360) that you should use if you want the data to be stored as a blob.

**Comment by danfairs** [comment]
Ah ok - that makes sense, thanks!

So I've made that change, and I've been able to remove the call to `register_encoder`, which is great. I've noticed something else though, which I'll look into further - I'll raise another issue if necessary.

Is there somewhere discussion takes place btw? GH issues doesn't feel like the right place for this sort of thing :)

**Comment by stevearc** [comment]
Yeah, I agree. I'd really like for github to have the option to set up some sort of forum or other discussion area for repos, but for now I think issues are good enough. If there were a larger community I'd consider setting up a google group or mailing list, but that's a bit of overkill.
